[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Maps/Stage1.Stage1
EditorStartupMap=/Game/Maps/Stage1.Stage1
GlobalDefaultGameMode=/Script/StreetsOfBerlin.BrawlerGameMode

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_Blank",NewGameName="/Script/StreetsOfBerlin")
GameViewportClientClassName=/Script/Engine.GameViewportClient

[/Script/Engine.RendererSettings]
; 2D-Look: keine automatische Belichtung, kein Bloom/Motion Blur, kein TAA-Verwischen
r.DefaultFeature.AutoExposure=False
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
r.DefaultFeature.Bloom=False
r.DefaultFeature.MotionBlur=False
r.DefaultFeature.LensFlare=False
r.AntiAliasingMethod=1
r.DefaultFeature.AntiAliasing=1
; Transluzente Sprites entlang der Tiefenachse sortieren (Kamera schaut entlang -Y)
TranslucentSortPolicy=SortAlongAxis
TranslucentSortAxis=(X=0.000000,Y=-1.000000,Z=0.000000)

[/Script/Paper2D.Paper2DSettings]
bEnableSpriteAtlasGroups=False

[Core.Log]
LogStreetsOfBerlin=Log
